set -g base-index 1
setw -g pane-base-index 1

set -g allow-rename on

set -g status-keys vi
setw -g mode-keys vi
setw -g monitor-activity on
set -g mouse on
set -g default-terminal "screen-256color"

# No delay for escape key press
set -sg escape-time 1

set -g history-limit 10000

# Open in the same path
bind-key v split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"

# Scroll
bind -n Pageup copy-mode -u

# Reload tmux config
bind r source-file ~/.tmux.conf

# replace C-b by C-a instead of using both prefixes
set -gu prefix2
unbind C-a
unbind C-b
set -g prefix C-Space
bind Space send-prefix

# THEME
set -g status-bg black
set -g status-fg white
set -g pane-active-border-fg "#87d6fd"
set -g pane-active-border-bg default
set -g window-status-current-bg "#afd700"
set -g window-status-current-fg "#005f00"
set -g window-status-current-attr bold
set -g window-status-separator ""
set -g window-status-current-format " #I:#W "
set -g window-status-format " #I:#W "
set -g status-left-length 30
set -g status-left '#[fg=green]#(whoami) '
set -g status-right '#[fg=yellow]#(~/bin/battery)#[default] #[fg=white]%a %h-%d %H:%M#[default]'

# Move window tab
bind-key < swap-window -t -
bind-key > swap-window -t +

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
