#!/bin/bash

URL=https://raw.githubusercontent.com/horta/dotfiles/main

/bin/bash -c "$(curl -fsSL $URL/install-deps)"

cd ~/
git clone -d 1 https://github.com/horta/dotfiles.git
cd dotfiles

./install
