#!/bin/bash

source $HOME/.functions

# Get OS informatio
OS=`uname -s`
OSREV=`uname -r`
OSARCH=`uname -m`

# XDG path
export XDG_CONFIG_HOME=$HOME/.config                                                                                           

# Go language
export GOPATH=$HOME/.go                                                                                                         

# Developing in C/C++
export CMAKE_BUILD_PARALLEL_LEVEL=4                                                                                            
export C_INCLUDE_PATH=/usr/local/include                                                                                       
export LIBRARY_PATH=/usr/local/lib                                                                                             

# Docs
export MANPAGER='nvim +Man!'                                                                                                   

# Search
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc                                                                                    

# Terminal
export CLICOLOR=1                                                                                                              
export fish_greeting=   

# Editor
export EDITOR=nvim
export VISUAL=$EDITOR

# Home paths
add_path $HOME/bin                                                                                                             
add_path $HOME/opt/cargo/bin                                                                                                  

# Brew paths
BREW_PREFIX=$(brew --prefix)
add_path $BREW_PREFIX/opt/ruby/bin                                                                                   
add_path $BREW_PREFIX/opt/cython/bin                                                                                 

#if [ $HORTA_HAS_BREW -eq 1 ];                                                                                                  
#then                                                                                                                           
#    add_path $HORTA_BREW_PREFIX/opt/ruby/bin                                                                                   
#    add_path $HORTA_BREW_PREFIX/lib/ruby/gems/3.0.0/bin                                                                        
#fi                                                                                                                             
#[ -d $HOME/.local/share/gem/ruby ] && add_path $HOME/.local/share/gem/ruby/3.0.0/bin                                           
#add_path $GOPATH/bin                                                                                                           
#if [ $HORTA_HAS_CARGO -eq 1 ];                                                                                                 
#then                                                                                                                           
#fi                                                                                                                             
#add_path /Users/horta/Library/Python/3.9/bin                                                                                   

source $HOME/.alias
source $HOME/.exec_fish
