#!/bin/bash

if type sudo >/dev/null 2>&1; then SUDO="sudo"; else SUDO=""; fi

if type apt >/dev/null 2>&1; then
    INSTALL="$SUDO apt-get -yqq install"
else
    INSTALL="$SUDO brew -y install"
fi

if ! type curl >/dev/null 2>&1; then
    $INSTALL curl
fi

if ! type git >/dev/null 2>&1; then
    $INSTALL git
fi

if ! type python3 >/dev/null 2>&1; then
    $INSTALL python3-pip
fi
